name: 'demo'

on:
  workflow_dispatch:

jobs:
  demo:
    name: 'demo'
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT
    steps:
      - name: get credentials
        id: get-credentials
        uses: 'mozillazg/alibabacloud-oidc-auth@v1'
        with:
          role-arn-to-assume: '${{ secrets.ROLE_ARN }}'
          oidc-provider-arn: '${{ secrets.OIDC_ARN }}'
          set-outputs: 'true'

      - uses: mozillazg/acr-login@008d514b0783ea9c0e889a27cf2e051710de1538
        with:
          region-id: ap-southeast-1
          access-key-id: ${{ steps.get-credentials.outputs.access-key-id }}
          access-key-secret: ${{ steps.get-credentials.outputs.access-key-secret }}
          security-token: ${{ steps.get-credentials.outputs.security-token }}
